In [82]:
import pandas as pd
import re
import uuid

In [83]:
# Load the CSV file
df = pd.read_csv('../raw/raw.csv')

In [84]:
df.head()

,Company Name,Job Title,Skills Requirements,Location,Mode,Job Description,Special Requirements,Duration,Type
0,Microsoft,SDE Intern (Frontend),"TypeScript, React.js, Redux, GraphQL, CSS-in-JS",Bengaluru,Hybrid,Join the Microsoft 365 team to build intuitive...,A strong portfolio or GitHub profile showcasin...,6 Months,SDE
1,Deloitte,Data Analytics & Strategy Intern,"SQL, Python (Pandas), Tableau, Power BI, Busin...",Pune,Offline,Work within our Technology Consulting practice...,Final year students from a quantitative field ...,3 Months,Data Science
2,IBM,Cybersecurity Analyst Intern,"Network Security, SIEM tools (QRadar), VAPT, P...",Delhi,Hybrid,Become a part of IBM's Security Operations Cen...,Certifications like CEH (Practical) or OSCP ar...,6 Months,SDE (Security)
3,Nokia,5G RAN Software Intern,"C++, Python, Linux, Telecommunications, LTE/5G...",Mumbai,Offline,Contribute to the development of next-generati...,"Pursuing a degree in ECE, CS, or a related fie...",6 Months,SDE (Telecom)
4,L&T,IoT Solutions Developer Intern,"Python, C++, Raspberry Pi/Arduino, MQTT, Azure...",Mumbai,Offline,Join L&T's Smart World & Communication divisio...,Hands-on experience with IoT hardware projects...,6 Months,SDE (IoT)

In [85]:
type_counts = df['Type'].value_counts(dropna=False)
location_counts = df['Location'].value_counts(dropna=False)
mode_counts = df['Mode'].value_counts(dropna=False)

print("Type bifurcation:\n", type_counts, "\n")
print("Location bifurcation:\n", location_counts, "\n")
print("Mode bifurcation:\n", mode_counts)

Type bifurcation:
 Type
Data Science          6
SDE                   5
SDE (DevOps)          3
Core Engineering      3
SDE (Security)        2
Product Management    2
IT Operations         2
SDE (Mobile)          2
Tech Consulting       2
SDE (Embedded)        2
SDE (Telecom)         1
SDE (IoT)             1
SDE (Gaming)          1
Design                1
SDE (AI)              1
SDE (Cloud)           1
SDE (Research)        1
SDE (AR/VR)           1
SDE (Firmware)        1
SDE (RPA)             1
SDE (GIS)             1
Name: count, dtype: int64

Location bifurcation:
 Location
Remote       7
Bengaluru    6
Delhi        5
Mumbai       5
Pune         4
Hyderabad    3
Gurugram     2
Chennai      2
Ahmedabad    2
Vadodara     1
Jaipur       1
Goa          1
Kochi        1
Name: count, dtype: int64

Mode bifurcation:
 Mode
Offline    21
Hybrid     12
Online      7
Name: count, dtype: int64

In [86]:
# Task 1: Convert Skills Requirements to list of strings
df['Skills Requirements'] = df['Skills Requirements'].str.split(',')

# Task 2: Extract only numbers from Duration column
df['Duration'] = df['Duration'].str.extract('(\d+)').astype(int)

<>:5: SyntaxWarning: invalid escape sequence '\d'
<>:5: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_26910/2507568844.py:5: SyntaxWarning: invalid escape sequence '\d'
  df['Duration'] = df['Duration'].str.extract('(\d+)').astype(int)

In [87]:
# decalaring the type mapping dictionary
type_mapping = {
    "Data Science": "SDE",
    "SDE": "SDE",
    "SDE (DevOps)": "CLOUD",
    "Core Engineering": "DATA_ENGINEER",
    "SDE (Security)": "CYBERSECURITY",
    "Product Management": "PRODUCT_MANAGER",
    "IT Operations": "CLOUD",
    "SDE (Mobile)": "SDE",
    "Tech Consulting": "SDE",
    "SDE (Embedded)": "SDE",
    "SDE (Telecom)": "DATA_ENGINEER",
    "SDE (IoT)": "SDE",
    "SDE (Gaming)": "GAME_DEV",
    "Design": "UI_UX",
    "SDE (AI)": "SDE",
    "SDE (Cloud)": "CLOUD",
    "SDE (Research)": "SDE",
    "SDE (AR/VR)": "GAME_DEV",
    "SDE (Firmware)": "SDE",
    "SDE (RPA)": "SDE",
    "SDE (GIS)": "DATA_ENGINEER",
}

In [88]:
df['Type Category'] = df['Type'].map(type_mapping)
df = df.drop(columns=['Type'])
df = df.rename(columns={'Type Category': 'JobType'})

In [89]:
# Generate random unique IDs
df.insert(0, "JobID", [uuid.uuid4().hex[:8] for _ in range(len(df))])

In [90]:
# Display the first few rows to verify changes
print("First 5 rows after processing:")

df.head()

First 5 rows after processing:

,JobID,Company Name,Job Title,Skills Requirements,Location,Mode,Job Description,Special Requirements,Duration,JobType
0,3e662cab,Microsoft,SDE Intern (Frontend),"[TypeScript, React.js, Redux, GraphQL, CSS...",Bengaluru,Hybrid,Join the Microsoft 365 team to build intuitive...,A strong portfolio or GitHub profile showcasin...,6,SDE
1,7e80b727,Deloitte,Data Analytics & Strategy Intern,"[SQL, Python (Pandas), Tableau, Power BI, ...",Pune,Offline,Work within our Technology Consulting practice...,Final year students from a quantitative field ...,3,SDE
2,aae11e75,IBM,Cybersecurity Analyst Intern,"[Network Security, SIEM tools (QRadar), VAPT...",Delhi,Hybrid,Become a part of IBM's Security Operations Cen...,Certifications like CEH (Practical) or OSCP ar...,6,CYBERSECURITY
3,9ed7d489,Nokia,5G RAN Software Intern,"[C++, Python, Linux, Telecommunications, L...",Mumbai,Offline,Contribute to the development of next-generati...,"Pursuing a degree in ECE, CS, or a related fie...",6,DATA_ENGINEER
4,f4f8ddda,L&T,IoT Solutions Developer Intern,"[Python, C++, Raspberry Pi/Arduino, MQTT, ...",Mumbai,Offline,Join L&T's Smart World & Communication divisio...,Hands-on experience with IoT hardware projects...,6,SDE

In [91]:
df.to_csv('../raw/jobPostings.csv', index=False)

In [92]:
df.head()

,JobID,Company Name,Job Title,Skills Requirements,Location,Mode,Job Description,Special Requirements,Duration,JobType
0,3e662cab,Microsoft,SDE Intern (Frontend),"[TypeScript, React.js, Redux, GraphQL, CSS...",Bengaluru,Hybrid,Join the Microsoft 365 team to build intuitive...,A strong portfolio or GitHub profile showcasin...,6,SDE
1,7e80b727,Deloitte,Data Analytics & Strategy Intern,"[SQL, Python (Pandas), Tableau, Power BI, ...",Pune,Offline,Work within our Technology Consulting practice...,Final year students from a quantitative field ...,3,SDE
2,aae11e75,IBM,Cybersecurity Analyst Intern,"[Network Security, SIEM tools (QRadar), VAPT...",Delhi,Hybrid,Become a part of IBM's Security Operations Cen...,Certifications like CEH (Practical) or OSCP ar...,6,CYBERSECURITY
3,9ed7d489,Nokia,5G RAN Software Intern,"[C++, Python, Linux, Telecommunications, L...",Mumbai,Offline,Contribute to the development of next-generati...,"Pursuing a degree in ECE, CS, or a related fie...",6,DATA_ENGINEER
4,f4f8ddda,L&T,IoT Solutions Developer Intern,"[Python, C++, Raspberry Pi/Arduino, MQTT, ...",Mumbai,Offline,Join L&T's Smart World & Communication divisio...,Hands-on experience with IoT hardware projects...,6,SDE

In [95]:
# Unique values and their counts for 'Type', 'Location', and 'Mode'
type_counts = df['JobType'].value_counts(dropna=False)
location_counts = df['Location'].value_counts(dropna=False)
mode_counts = df['Mode'].value_counts(dropna=False)

print("Type bifurcation:\n", type_counts, "\n")
print("Location bifurcation:\n", location_counts, "\n")
print("Mode bifurcation:\n", mode_counts)

Type bifurcation:
 JobType
SDE                22
CLOUD               6
DATA_ENGINEER       5
CYBERSECURITY       2
GAME_DEV            2
PRODUCT_MANAGER     2
UI_UX               1
Name: count, dtype: int64

Location bifurcation:
 Location
Remote       7
Bengaluru    6
Delhi        5
Mumbai       5
Pune         4
Hyderabad    3
Gurugram     2
Chennai      2
Ahmedabad    2
Vadodara     1
Jaipur       1
Goa          1
Kochi        1
Name: count, dtype: int64

Mode bifurcation:
 Mode
Offline    21
Hybrid     12
Online      7
Name: count, dtype: int64

In [94]:
newdata = df.drop(columns=['JobID'])
newdata.to_csv('../raw/jobdataforDB.csv', index=False)

In [ ]:
# Filter rows where JobType is 'GAME_DEV' and display their 'Skills Requirements'
game_dev_skills = df[df['JobType'] == 'GAME_DEV']['Skills Requirements']
print("GAME_DEV Skills Requirements:\n", game_dev_skills)